# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Limit clone depth, does it speed up the build?
git:
  depth: false

# Blacklist
branches:
  except:
    - gh-pages

# Install dependencies
addons:
  apt:
    packages:
      # for deploy_keywords.sh
      #- doxygen
      #- xsltproc

env:
  global:
  - CHANGELOG_NAME="Travis CI - Keywords Bot"
  - CHANGELOG_EMAIL=travis@example.com
  - CHANGELOG_BRANCH=master

script:
  #- make
  - echo "script"

after_success:
  - chmod u+x deploy_keywords.sh
  #- ./deploy_keywords.sh
  - chmod u+x deploy_version.sh
  - ./deploy_version.sh

