#language: ruby
#cache: bundler

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - xsltproc


install:
  - chmod u+x deploy.sh
  - ./deploy.sh
#  - ./deploy.sh

env:
  global:
  - CHANGELOG_BRANCH=master
