# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Limit clone depth, does it speed up the build?
git:
  depth: false

# Blacklist
branches:
  except:
    - gh-pages

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - xsltproc

env:
  global:
  - CHANGELOG_BRANCH=master

install:
  - chmod u+x deploy.sh

script:
  - make

after_success:
  - ./deploy.sh

