# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

env:
  global:
  - CHANGELOG_BRANCH=master

install:
  - chmod u+x deploy.sh

script:
  - ./deploy.sh
