# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Limit clone depth, does it speed up the build?
git:
  depth: false

# Blacklist
branches:
  except:
    - gh-pages

# Install dependencies
addons:
  apt:
    packages:
      # for deploy_keywords.sh
      - doxygen
      - xsltproc

env:
  global:
  - CONFIG_KEYWORDS_NAME="Travis CI - Keywords Bot"
  - CONFIG_KEYWORDS_EMAIL=travis@example.com
  - CONFIG_KEYWORDS_BRANCH=master
  - CONFIG_VERSION_NAME="Travis CI - Version Bot"
  - CONFIG_VERSION_EMAIL="$CONFIG_KEYWORDS_EMAIL"
  - CONFIG_VERSION_BRANCH="$CONFIG_KEYWORDS_BRANCH"
  - CONFIG_CHANGELOG_NAME="Travis CI - Changelog Bot"
  - CONFIG_CHANGELOG_EMAIL="$CONFIG_KEYWORDS_EMAIL"
  - CONFIG_CHANGELOG_BRANCH="$CONFIG_KEYWORDS_BRANCH"
  - CONFIG_REMOTE_NAME="Travis CI - Remote Bot"
  - CONFIG_REMOTE_EMAIL="$CONFIG_KEYWORDS_EMAIL"
  - CONFIG_REMOTE_BRANCH=test

script:
  #- make
  - echo "script"

#after_success:
deploy:
  - provider: script
    script: bash ./deploy_keywords.sh
    on:
      #branch: dev
      branch: master
      #all_branches: true
  - provider: script
    script: bash ./deploy_version.sh
    on:
      branch: master
  - provider: script
    script: bash ./deploy_changelog.sh
    on:
      branch: master
  - provider: script
    script: bash ./.deploy_remote.sh
    on:
      branch: test

